Name:           ros-kinetic-jskeus
Version:        1.0.13
Release:        1%{?dist}
Summary:        ROS jskeus package

Group:          Development/Libraries
License:        BSD
URL:            http://euslisp.github.io/jskeus/manual.html
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-euslisp
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-euslisp

%description
EusLisp software developed and used by JSK at The University of Tokyo

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Aug 03 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.13-1
- Autogenerated by Bloom

* Tue Aug 02 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.13-0
- Autogenerated by Bloom

* Tue Apr 05 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.12-0
- Autogenerated by Bloom

